USE shop_quan_ao;

CREATE TABLE TAIKHOAN (
    TenDN VARCHAR(30) PRIMARY KEY,
    MatKhau VARCHAR(255) NOT NULL,
    VaiTro ENUM('admin', 'customer') NOT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DANHMUC (
    MaDM CHAR(5) PRIMARY KEY,
    TenDM VARCHAR(100) NOT NULL,
    MoTa TEXT,
    TrangThai BOOLEAN DEFAULT TRUE
);

CREATE TABLE THUONGHIEU (
    MaTH CHAR(5) PRIMARY KEY,
    TenTH VARCHAR(100) NOT NULL,
    MoTa TEXT,
    QuocGia VARCHAR(50)
);