USE shop_quan_ao;

CREATE TABLE GIOHANG (
    MaKH CHAR(5),
    MaSP CHAR(5),
    SoLuong INT NOT NULL,
    KichThuoc ENUM('S', 'M', 'L', 'XL', 'XXL'),
    MauSac VARCHAR(30),
    NgayThem TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaKH, MaSP, KichThuoc, MauSac),
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE DANHGIA (
    MaDG INT AUTO_INCREMENT PRIMARY KEY,
    MaKH CHAR(5) NOT NULL,
    MaSP CHAR(5) NOT NULL,
    Diem INT,
    NoiDung TEXT,
    NgayDG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);