USE shop_quan_ao;

CREATE TABLE KHACHHANG (
    MaKH CHAR(5) PRIMARY KEY,
    TenKH VARCHAR(50) NOT NULL,
    SDT VARCHAR(15) UNIQUE,
    Email VARCHAR(50) UNIQUE,
    DiaChi TEXT,
    TenDN VARCHAR(30) UNIQUE,
    NgayDangKy TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TenDN) REFERENCES TAIKHOAN(TenDN)
);

CREATE TABLE ADMIN (
    MaAdmin CHAR(5) PRIMARY KEY,
    TenAdmin VARCHAR(50) NOT NULL,
    Email VARCHAR(50),
    TenDN VARCHAR(30) UNIQUE,
    FOREIGN KEY (TenDN) REFERENCES TAIKHOAN(TenDN)
);

CREATE TABLE TRANGTHAIDON (
    MaTT CHAR(3) PRIMARY KEY,
    TenTT VARCHAR(50) NOT NULL
);

CREATE TABLE DONHANG (
    MaDH CHAR(5) PRIMARY KEY,
    MaKH CHAR(5) NOT NULL,
    NgayLap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TongTien DECIMAL(12,2) NOT NULL,
    DiaChiGiaoHang TEXT,
    SDTNhanHang VARCHAR(15),
    MaTT CHAR(3) DEFAULT '001',
    GhiChu TEXT,
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaTT) REFERENCES TRANGTHAIDON(MaTT)
);

CREATE TABLE CHITIETDH (
    MaDH CHAR(5),
    MaSP CHAR(5),
    SoLuong INT NOT NULL,
    DonGia DECIMAL(10,2) NOT NULL,
    ThanhTien DECIMAL(12,2) NOT NULL,
    KichThuoc ENUM('S', 'M', 'L', 'XL', 'XXL'),
    MauSac VARCHAR(30),
    PRIMARY KEY (MaDH, MaSP),
    FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH),
    FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);